### ISSUE TITLE
Searching - no results

### ISSUE THREAD

**Issue by aniveera1** [rahulssheth1/Elevated-Pitch-Main-Repo#10]
Searching for a term that has no results and then clicking on a category (people, university, etc.) returns a blank page from which there are no buttons to return anywhere

**Comment by rahulssheth1** [comment]
Added masthead to allow for movement throughout the feed. Setting up the search controller so if you yield no results in a certain category, it will show everything in that list

**Comment by rahulssheth1** [comment]
Finished issue
